apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-windows.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: frontend-api-nginx
  name: frontend-api-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend-api-nginx
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-windows.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: frontend-api-nginx
    spec:
      containers:
        - image: eladio59/recycling:front
          name: frontend
          ports:
            - containerPort: 4200
              protocol: TCP
      restartPolicy: Always
