apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: springboot-api-claim0
  name: springboot-api-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
