apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-windows.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: springboot-api
  name: springboot-api
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: springboot-api
