apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-windows.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: springboot-api
  name: springboot-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: springboot-api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-windows.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: springboot-api
    spec:
      containers:
        - env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo:27017/your_database_name
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          image: eladio59/recycling:springboot-mongodb
          name: springboot-api
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
